src/views/front.py
# -*- coding: utf-8 -*-
"""
    views.front
    ~~~~~~~~~~~

    Frontend view functions.

    :copyright: (c) 2019 by staugur.
    :license: BSD 3-Clause, see LICENSE for more details.
"""

from flask import Blueprint, render_template, make_response, redirect, \
    url_for, current_app, Response, g, abort
from utils.web import admin_apilogin_required, anonymous_required, \
    login_required, check_activate_token, dfr
from utils.tool import is_true, rsp, string_types
from utils._compat import PY2, text_type

bp = Blueprint("front", "front")


@bp.route("/")
def index():
    return render_template("public/index.html")


@bp.route("/login")
@anonymous_required
def login():
    if g.cfg.site_auth:
        so = current_app.extensions["hookmanager"].proxy(g.cfg.site_auth)
        if so and hasattr(so, "login_handler"):
            result = so.login_handler()
            if result and isinstance(result, Response):
                return result
    return render_template("public/login.html")


@bp.route("/logout")
@login_required
def logout():
    if g.cfg.site_auth:
        so = current_app.extensions["hookmanager"].proxy(g.cfg.site_auth)
        if so and hasattr(so, "logout_handler"):
            result = so.logout_handler()
            if result and isinstance(result, Response):
                return result
    res = make_response(redirect(url_for("front.index")))
    res.set_cookie(key='dSid',  value='', expires=0)
    return res


@bp.route("/register")
@anonymous_required
def register():
    if is_true(g.cfg.register):
        return render_template("public/register.html")
    else:
        return abort(404)


@bp.route("/control/myself")
@login_required
def my():
    return render_template("control/my.html")


@bp.route("/control/admin")
@admin_apilogin_required
def admin():
    return render_template("control/admin.html")


@bp.route("/picbed.user.js")
def userscript():
    if g.signin and is_true(g.userinfo.ucfg_userscript):
        resp = make_response(render_template("public/userscript.js"))
        resp.headers['Content-type'] = 'application/javascript; charset=utf-8'
        return resp
    else:
        return abort(404)


@bp.route("/activate/<token>")
def activate(token):
    res = dfr(check_activate_token(token))
    if res["code"] == 0:
        data = res["data"]
        Action = data["Action"]

        if Action == "verifyEmail":
            username = data["username"]
            checkmail = data["email"]
            uk = rsp("account", username)
            usermail = g.rc.hget(uk, "email")
            success = False
            url = url_for("front.my") if g.signin else url_for("front.login")
            if checkmail == usermail:
                g.rc.hset(uk, "email_verified", 1)
                success = True
            return render_template("public/go.html", url=url, success=success)

        elif Action == "resetPassword":
            username = data["username"]
            return render_template(
                "public/forgot.html", is_reset=True, token=token, user=username
            )

    else:
        name = res["msg"]
        if PY2 and not isinstance(name, text_type):
            name = name.decode("utf-8")
        return render_template(
            "public/error.html", code=res["code"], name=name
        )


@bp.route("/forgot")
@anonymous_required
def forgot():
    return render_template("public/forgot.html")


@bp.route("/extendpoint/<hook_name>/", defaults=dict(route_name=None))
@bp.route("/extendpoint/<hook_name>/<route_name>")
def ep(hook_name, route_name):
    obj = current_app.extensions["hookmanager"].proxy(hook_name)
    if obj and hasattr(obj, "route"):
        rule = obj.route()
        if isinstance(rule, string_types):
            return rule
        elif isinstance(rule, dict) and route_name in rule:
            rst = rule[route_name]
            if callable(rst):
                if not isinstance(rst, Response):
                    return rst()
            return rst
    return abort(404)


@bp.route("/feed")
@login_required
def feed():
    pipe = g.rc.pipeline()
    uk = rsp("index", "user", g.userinfo.username)
    fields = ["title", "filename", "ctime", "user", "src"]
    for sha in g.rc.smembers(uk):
        pipe.hmget(rsp("image", sha), *fields)
    result = pipe.execute()
    data = [dict(zip(fields, i)) for i in result if i]
    xml = render_template('public/feed.xml', items=sorted(
        data,
        key=lambda k: int(k.get('ctime', 0)),
        reverse=True
    )[:10])
    response = make_response(xml)
    response.headers['Content-Type'] = 'application/xml'
    return response

src/templates/ref/header.html
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta name="author" content="SaintIC">
<meta name="keywords" content="{{ g.site.seo_keywords or 'SaintIC,picbed,sapic,sapicd,图床' }}">
<meta name="description" content="{{ g.site.seo_description or Doc }}">
<link rel="alternate" type="application/atom+xml" title="{{ g.userinfo.ucfg_feed_name or ('The RSS of ' + g.userinfo.username) }} - {{ g.site_name }} Feed" href="{{ url_for('front.feed') }}">
<link href="{{ g.site.favicon or url_for('static', filename='img/favicon.png') }}" rel="icon" type="image/x-icon" />
<link href="{{ g.site.favicon or url_for('static', filename='img/favicon.png') }}" rel="shortcut icon" type="image/x-icon" />

src/templates/ref/nav.html
<!--导航-->
<a class="layui-logo" href="{{ url_for('front.index') }}">
    <img src="{{ g.site.logo or url_for('static', filename='img/logo.png') }}">
</a>
<ul class="layui-nav layui-layout-right">
    <li class="layui-nav-item" id="verTip"></li>
    <li class="layui-nav-item {% if request.endpoint == 'front.index' %}layui-this{% endif %}">
        <a {% if request.endpoint != 'front.index' %} href="{{ url_for('front.index') }}" {% endif %}><i class="saintic-icon saintic-icon-home"></i> 首页</a>
    </li>
    {% if g.signin %}
    <li class="layui-nav-item">
        <a href="javascript:;">
            <img id="avatar" src="{{ g.userinfo.avatar or url_for('static', filename='img/defaultAvatar.png') }}" class="layui-nav-img">
            <cite id="nickname">{{ g.userinfo.nickname or g.userinfo.username }}</cite>
        </a>
        <dl class="layui-nav-child">
            <dd><a {% if request.endpoint != "front.my" %} href="{{ url_for('front.my', _anchor='!profile') }}" {% endif %}><i class="saintic-icon saintic-icon-user"></i> 个人资料</a></dd>
            <dd><a {% if request.endpoint != "front.my" %} href="{{ url_for('front.my', _anchor='!setting') }}" {% endif %}><i class="saintic-icon saintic-icon-setting"></i> 用户设置</a></dd>
            <dd><a {% if request.endpoint != "front.my" %} href="{{ url_for('front.my', _anchor='!picbed') }}" {% endif %}><i class="saintic-icon saintic-icon-user-album"></i> 我的图片</a></dd>
            <dd><a href="{{ url_for('front.feed') }}" target="_blank"><i class="saintic-icon saintic-icon-rss"></i> 我的RSS</a></dd>
            {{ intpl("nav") }}
            {% if g.is_admin %}
            <dd><a href="{{ url_for('front.admin') }}"><i class="saintic-icon saintic-icon-site-manager"></i> 站点管理</a></dd>
            {% endif %}
            <hr class="navbar-divider">
            <dd><a href="{{ url_for('front.logout') }}"><i class="saintic-icon saintic-icon-logoff"></i> 登出</a></dd>
        </dl>
    </li>
    {% else %}
    <li class="layui-nav-item {% if request.endpoint == 'front.login' %}layui-this{% endif %}">
        <a {% if request.endpoint != 'front.login' %} href="{{ url_for('front.login') }}" {% endif %}><i class="saintic-icon saintic-icon-login"></i> 登录</a>
    </li>
    {% if is_true(g.site.register) %}
    <li class="layui-nav-item {% if request.endpoint == 'front.register' %}layui-this{% endif %}">
        <a {% if request.endpoint != 'front.register' %} href="{{ url_for('front.register') }}" {% endif %}><i class="saintic-icon saintic-icon-register"></i> 注册</a>
    </li>
    {% endif %}
    {% endif %}
</ul>

src/templates/ref/upload_show.html
{% raw %}
<script id="upload_show_tpl" type="text/html">
<div style="padding: 15px">
    {{# if (d.is_control === true) { }}
    <p>文件名：{{ d.filename }}</p>
    <p>唯一标识：{{ d.picbed.str2star(d.sha, 5, -10) }} <sub>
        <a href="javascript:;" title="复制" id="copySha" data-sha="{{ d.sha }}">
            <i class="saintic-icon saintic-icon-copy"></i>
        </a></sub>
    </p>
    <p>上传时间：{{ d.ctime }}</p>
    <p>所属用户：{{ d.user }}</p>
    <p>
        <div class="layui-form" action="">
            所属相册：<input type="text" name="album" autocomplete="off" value="{{ d.album || '' }}" list="list_user_albums" class="my-input">
            <datalist id="list_user_albums"></datalist>
            <input type="hidden" name="sha" autocomplete="off" value="{{ d.sha }}">
            <button type="button" title="更新相册名" class="layui-btn layui-btn-xs layui-btn-radius" lay-submit lay-filter="updateAlbumSubmit"><i class="layui-icon layui-icon-ok"></i></button>
        </div>
    </p>
    <p>图片状态：
        {{# if (d.status === 'enabled') { }}
        <scan style="color:green">{{ d.status }}</scan>
        {{# } else { }}
        <scan style="color:red">{{ d.status }}</scan>
        {{# } }}
    </p>
    {{# } else { }}
    <p>文件名：<a href="{{ d.api }}" target="_blank">{{ d.filename }}</a></p>
    {{# } }}
    <p>图片保存者：{{ d.sender }}</p>
    <div class="layui-row layui-col-space2">
        <div class="layui-col-xs12 layui-col-sm2 layui-col-md2">
            <a href="{{ d.src }}" target="_blank" {{# if (d.is_control === true){ }}download="{{ d.filename }}"{{# } }}>
                <img src="{{ d.get_src('loadmypic') }}" style="max-width:80px;padding-top:61px;">
            </a>
        </div>
        <div class="layui-col-xs12 layui-col-sm10 layui-col-md10">
            <div class="layui-tab layui-tab-brief">
                <ul class="layui-tab-title">
                    <li class="layui-this">URL</li>
                    <li>HTML</li>
                    <li>rST</li>
                    <li>Markdown</li>
                </ul>
                <div class="layui-tab-content">
                    <div class="layui-tab-item layui-show">
                        <textarea class="layui-textarea" readonly id="url">{{ d.get_src('url') }}</textarea>
                        <button type="button" class="layui-btn layui-btn-sm layui-btn-fluid upload_show_copy"
                            data-copyid="#url">复制</button>
                    </div>
                    <div class="layui-tab-item">
                        <textarea class="layui-textarea" readonly
                            id="html">&lt;img src="{{ d.get_src('html') }}" title="{{ d.title }}" alt="{{ d.filename }}"&gt;</textarea>
                        <button type="button" class="layui-btn layui-btn-sm layui-btn-fluid upload_show_copy"
                            data-copyid="#html">复制</button>
                    </div>
                    <div class="layui-tab-item">
                        <textarea class="layui-textarea" readonly id="rst">.. image:: {{ d.get_src('rst') }}</textarea>
                        <button type="button" class="layui-btn layui-btn-sm layui-btn-fluid upload_show_copy"
                            data-copyid="#rst">复制</button>
                    </div>
                    <div class="layui-tab-item">
                        <textarea class="layui-textarea" readonly
                            id="markdown">![{{ d.filename }}]({{ d.get_src('markdown') }})</textarea>
                        <button type="button" class="layui-btn layui-btn-sm layui-btn-fluid upload_show_copy"
                            data-copyid="#markdown">复制</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</script>
{% endraw %}